build:
  tags: [build]
  script:
    - docker-compose build
    - docker-compose push
    - docker-compose up
    - chmod 400 $SSH_RSA
    - rsync --delete -Pav -e "ssh -i $SSH_RSA" /opt/mathcrowd-docs/html/ root@www.mathcrowd.cn:/var/www/sphinx
